### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by elhawaryna** [jack2015/openpli-dreambox-oe-core#1]
ERROR: dvdfs-0.2-r1 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="2404"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/elhawary/Desktop/openpli-dreambox-oe-core/openembedded-core/scripts:/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/dvdfs/0.2-r1/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/dvdfs/0.2-r1/recipe-sysroot/usr/bin/crossscripts:/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/dvdfs/0.2-r1/recipe-sysroot-native/usr/sbin:/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/dvdfs/0.2-r1/recipe-sysroot-native/usr/bin:/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/dvdfs/0.2-r1/recipe-sysroot-native/sbin:/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/dvdfs/0.2-r1/recipe-sysroot-native/bin:/home/elhawary/Desktop/openpli-dreambox-oe-core/bitbake/bin:/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/elhawary"; /usr/bin/env wget -t 2 -T 30 --passive-ftp -O /home/elhawary/Desktop/openpli-dreambox-oe-core/sources/dvdfs-0.2.tar.gz.tmp -P /home/elhawary/Desktop/openpli-dreambox-oe-core/sources 'http://www.jspenguin.org/software/dvdfs/dvdfs-0.2.tar.gz' --progress=dot -v failed with exit code 4, no output
ERROR: dvdfs-0.2-r1 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://www.jspenguin.org/software/dvdfs/dvdfs-0.2.tar.gz')
ERROR: Logfile of failure stored in: /home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/dvdfs/0.2-r1/temp/log.do_fetch.4128714
ERROR: Task (/home/elhawary/Desktop/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/fuse/dvdfs_0.2.bb:do_fetch) failed with exit code '1'

**Comment by gjstroom** [comment]
copy this one:
https://github.com/OpenPLi/openpli-oe-core/raw/develop/meta-openpli/recipes-multimedia/fuse/dvdfs_0.2.bb

**Comment by jack2015** [comment]
fixed
