### ISSUE TITLE
ERROR dm820

### ISSUE THREAD

**Issue by elhawaryna** [jack2015/openpli-dreambox-oe-core#2]
ERROR: openpli-enigma2-image-1.0-r0 do_rootfs: Unable to install packages. Command '/home/elhawary/1/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/openpli-enigma2-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/elhawary/1/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/openpli-enigma2-image/1.0-r0/opkg.conf -t /home/elhawary/1/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/openpli-enigma2-image/1.0-r0/temp/ipktemp/ -o /home/elhawary/1/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/openpli-enigma2-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install 3rd-party-feed-configs aio-grab avahi-daemon ca-certificates cdtextinfo cifs-utils distro-feed-configs dropbear e2fsprogs-e2fsck e2fsprogs-mke2fs e2fsprogs-tune2fs enigma2 enigma2-plugin-extensions-audiosync enigma2-plugin-extensions-autobackup enigma2-plugin-extensions-bitrate enigma2-plugin-extensions-blurayplayer enigma2-plugin-extensions-cdinfo enigma2-plugin-extensions-cutlisteditor enigma2-plugin-extensions-dvdplayer enigma2-plugin-extensions-fancontrol2 enigma2-plugin-extensions-filecommander enigma2-plugin-extensions-graphmultiepg enigma2-plugin-extensions-mediaplayer enigma2-plugin-extensions-mediascanner enigma2-plugin-extensions-moviecut enigma2-plugin-extensions-openwebif enigma2-plugin-extensions-oscamstatus enigma2-plugin-extensions-pictureplayer enigma2-plugin-extensions-ppanel enigma2-plugin-extensions-systemtools enigma2-plugin-extensions-youtube enigma2-plugin-softcams-oscam enigma2-plugin-systemplugins-cablescan enigma2-plugin-systemplugins-commoninterfaceassignment enigma2-plugin-systemplugins-fastscan enigma2-plugin-systemplugins-hotplug enigma2-plugin-systemplugins-networkbrowser enigma2-plugin-systemplugins-osd3dsetup enigma2-plugin-systemplugins-osdpositionsetup enigma2-plugin-systemplugins-positionersetup enigma2-plugin-systemplugins-satfinder enigma2-plugin-systemplugins-softwaremanager enigma2-plugin-systemplugins-videoenhancement enigma2-plugin-systemplugins-videomode enigma2-plugin-systemplugins-videotune enigma2-plugin-systemplugins-wirelesslan fakelocale firmware-carl9170 firmware-htc7010 firmware-htc9271 firmware-rt2870 firmware-rt73 firmware-rtl8188eu firmware-rtl8192eu firmware-rtl8712u firmware-zd1211 fuse-exfat glibc-binary-localedata-en-gb hdparm kernel-module-ath9k-htc kernel-module-carl9170 kernel-module-r8712u kernel-module-rt2500usb kernel-module-rt2800usb kernel-module-rt73usb kernel-module-rtl8187 kernel-module-zd1211rw kernel-params libavahi-client libsoup-2.4 modutils-loadscript nfs-utils nfs-utils-client ntpdate openpli-bootlogo openssh-sftp-server opkg packagegroup-base packagegroup-core-boot parted python-ipaddress python-netifaces python-pysmb rtl8188eu rtl8192eu run-postinsts sdparm settings-autorestore tuxbox-common tzdata util-linux-ionice volatile-media vsftpd' returned 255:
 * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'kernel-module-ath9k-htc'.

ERROR: Logfile of failure stored in: /home/elhawary/1/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/openpli-enigma2-image/1.0-r0/temp/log.do_rootfs.512185
ERROR: Task (/home/elhawary/1/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6269 tasks of which 5791 didn't need to be rerun and 1 failed.

**Comment by jack2015** [comment]
Delete the 'build' directory and completely recompile.

**Comment by elhawaryna** [comment]
Thank you very much, two problems remain
The first
There is no association between the files folder
in the track
openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/files
When building the image though write the correct path to the file
package-index.bb
/home/elhawary/1/openpli-dreambox-oe-core/meta-openpli/recipes-core/package-index/package-index.bb
The second is that there is a problem in the boot folder that causes the image to not boot and the device to freeze, and this is only in the 820
And when changing the boot folder, it is booted easily, and I mean to build an image from the fairbird files here
https://github.com/fairbird/openpli-dreambox-oe-core/tree/develop/meta-dreambox/recipes-linux
Thank you very much for helping me

**Comment by jack2015** [comment]
I have no DM820. so, can not test.
