### ISSUE TITLE
DM800se image

### ISSUE THREAD

**Issue by Torros-Team** [jack2015/openpli-dreambox-oe-core#27]
hello friend or in need of a favor I compiled a DM800se images with your openpli-dreambox-oe-core until everything is ok but when I load it on my Dreambox it starts but then it locks in bootloop to some idea what it depends on thanks a lot

**Comment by jack2015** [comment]
SIM ORIGINAL,
SIM A8P,
SIM Estar,
SIM 210,
Japhar Ferrari Sim ???

**Comment by Torros-Team** [comment]
Hello friend sorry not or understood

**Comment by jack2015** [comment]
https://www.linuxsat-support.com/board/101-dm800se-dm800sev2-images/

**Comment by Torros-Team** [comment]
Hello friend good morning that I saw it but I mean a problem that I compiled images with your openpli-dreambox-oe-core and compiled it only that when I install it on the DM800se it activates up to the bootlogos and then it blocks in bootloop
