### ISSUE TITLE
Kernel-Patch Files N/A - dreamboxupdate.com down! 

### ISSUE THREAD

**Issue by Token2K** [jack2015/openpli-dreambox-oe-core#6]
when trying to make a compile for the dm520/dm900, it terminates with error, because dreamboxupdate.com is down.
do you have an alternative ready - or can I give up building with it? 
so it's about an alternative for the kernel patches, etc.

DM520-original:
WARNING: linux-dreambox-3.4-r14 do_fetch: Failed to fetch URL http://dreamboxupdate.com/download/kernel-patches/linux-dreambox-3.4-30070c78a23d461935d9db0b6ce03afc70a10c51.patch.xz;apply=yes;name=dream-patch, attempting MIRRORS if available

DM900-original:
WARNING: linux-dreambox-3.14-r0 do_fetch: Failed to fetch URL http://dreamboxupdate.com/download/kernel-patches/linux-dreambox-3.14-6fa88d2001194cbff63ad94cb713b6cd5ea02739.patch.xz;apply=yes;name=dream-patch, attempting MIRRORS if available

linux-dreambox_3.4.bb and linux-dreambox_3.14.bb (and many more?) required updates!
(see here: https://github.com/oe-alliance/oe-alliance-core/commit/9132d0a618b31b0e2cf3175cf0ecd834cd3fd970)

**Comment by jack2015** [comment]
fixed
